import pandas as pd


def sample_frame() -> pd.DataFrame:
    """Get a sample of what data looks like.

    A lot of packages and tests can expect to have a shape of the real data.
    """
    return pd.DataFrame(
        {
            "age": [56, 57, 37, 40, 25, 31, 49, 33, 62, 44, 29, 51],
            "job": [
                "housemaid",
                "services",
                "services",
                "admin.",
                "technician",
                "blue-collar",
                "entrepreneur",
                "retired",
                "admin.",
                "management",
                "student",
                "unemployed",
            ],
            "marital": [
                "married",
                "married",
                "single",
                "divorced",
                "single",
                "married",
                "married",
                "married",
                "single",
                "divorced",
                "single",
                "married",
            ],
            "education": [
                "basic.4y",
                "high.school",
                "high.school",
                "university.degree",
                "professional.course",
                "basic.9y",
                "university.degree",
                "basic.6y",
                "high.school",
                "university.degree",
                "high.school",
                "basic.4y",
            ],
            "default": ["no", "unknown", "no", "no", "no", "no", "unknown", "no", "no", "no", "no", "no"],
            "housing": ["no", "no", "yes", "yes", "no", "yes", "yes", "no", "yes", "no", "yes", "no"],
            "loan": ["no", "no", "no", "yes", "no", "no", "no", "no", "no", "yes", "no", "no"],
            "contact": [
                "telephone",
                "telephone",
                "cellular",
                "cellular",
                "cellular",
                "telephone",
                "cellular",
                "cellular",
                "telephone",
                "cellular",
                "cellular",
                "cellular",
            ],
            "month": ["may", "may", "jun", "jul", "aug", "may", "nov", "apr", "jun", "jul", "sep", "oct"],
            "day_of_week": ["mon", "tue", "wed", "thu", "fri", "mon", "tue", "wed", "thu", "fri", "mon", "tue"],
            "duration": [261, 149, 226, 151, 307, 198, 139, 512, 244, 91, 380, 175],
            "campaign": [1, 1, 1, 2, 1, 3, 2, 1, 4, 1, 2, 6],
            "pdays": [999, 999, 999, 999, 3, 999, 6, 999, 999, 999, 12, 999],
            "previous": [0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0],
            "poutcome": [
                "nonexistent",
                "nonexistent",
                "nonexistent",
                "nonexistent",
                "success",
                "nonexistent",
                "failure",
                "nonexistent",
                "nonexistent",
                "nonexistent",
                "success",
                "nonexistent",
            ],
            "emp.var.rate": [1.1, 1.1, 1.4, 1.4, -1.8, 1.1, -0.1, 1.4, 1.4, 1.4, -1.1, -1.1],
            "cons.price.idx": [
                93.994,
                93.994,
                94.465,
                93.918,
                92.893,
                93.994,
                93.2,
                93.918,
                94.465,
                93.918,
                94.199,
                94.601,
            ],
            "cons.conf.idx": [-36.4, -36.4, -41.8, -42.7, -46.2, -36.4, -42.0, -42.7, -41.8, -42.7, -37.5, -49.5],
            "euribor3m": [4.857, 4.857, 4.962, 4.961, 1.313, 4.857, 4.191, 4.961, 4.962, 4.961, 0.884, 0.959],
            "nr.employed": [
                5191.0,
                5191.0,
                5228.1,
                5228.1,
                5099.1,
                5191.0,
                5195.8,
                5228.1,
                5228.1,
                5228.1,
                4963.6,
                4963.6,
            ],
            "y": ["no", "no", "no", "no", "yes", "no", "yes", "yes", "no", "no", "yes", "no"],
        }
    )
